force-app/main/default/objects/Custom_Experience_Cloud_Setting__mdt/Custom_Experience_Cloud_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Used by the installed 
    package called Configurable Self Registration &amp; Login For Experience Cloud to configure component behaviour, including logging. Login uses the Login Settings record and Self Registration uses the Self Registration Settings record. Form fields are configured separately in Custom Login Configuration Fields and Custom Registration Configuration Fields.</description>
    <label>Custom Experience Cloud Setting</label>
    <pluralLabel>Custom Experience Cloud Settings</pluralLabel>
</CustomObject>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Experience_Cloud_Setting__mdt/fields/Enable__c.field-meta.xml
<CustomField>
    <fullName>Enable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable</label>
    <type>Checkbox</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Experience_Cloud_Event__e/Experience_Cloud_Event__e.object-meta.xml
<CustomObject>
    <label>Experience Cloud Event</label>
    <pluralLabel>Experience Cloud Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Experience_Cloud_Event__e/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience_Cloud_Event__e/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Experience_Cloud_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/classes/SiteUtilities.cls
/***************************************************************************************************************
 * AUTHOR         : Jamie Lowe (Salesforce)
 * CREATE DATE    : 13/04/2024
 * @description Apex controller to provide common functions between SiteRegistration, SiteLogin and others in the future
 ***************************************************************************************************************/
public with sharing class SiteUtilities {
    
    /**
    * @description Simple method to wrap Object's Key > String conversion for easy re-use.
    * @param valueToConvert - pass in an object and convert to a String value
    * @return String of passed object value
    */
    @AuraEnabled
    public static String convertToString(Object valueToConvert) {
        if(valueToConvert != null) {
            return String.valueOf(valueToConvert);
        }
        return '';
    }

    /**
    * @description Simple method to wrap Object > Boolean conversion for easy re-use.
    * @param valueToConvert - pass in an object and convert to a Boolean value
    * @return Boolean of passed object value
    */
    @AuraEnabled
    public static Boolean convertToBoolean(Object valueToConvert) {
        if(valueToConvert != null) {
            return Boolean.valueOf(valueToConvert);
        }
        return false;
    }    

    /** 
     * @description Create a Platform Event (Error Log) which a Flow subscribes. The platform event contains a list of messages to log in a custom object. Off by default, turn on in the Custom Metadata Types.
     * @param loggingEnabled - Passes in the LWC property panel setting to turn logging on or off in a custom object called 'Self Registration Log'
     * @param message - a list of messages to store on the Platform Event
     * @param logType - the type of error to log, either 'Information' or 'Log'
     * @param componentName - the name of the component that is calling this function
     */
    @AuraEnabled
    public static void createLogEntry(Boolean loggingEnabled, String message, String logType, String componentName){
       try {
            if(loggingEnabled) {
                Experience_Cloud_Event__e newLog = new Experience_Cloud_Event__e();
                newLog.Message__c = message;
                newLog.Log_Type__c = logType;
                newLog.Component_Name__c = componentName;
                Eventbus.publish(newLog);
            } 
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description Checks to see if the Logging setting is activated.
    * @param settingName - pass in the settingName which is related to the component
    * @return true/false depending on setting value.
    */
    @AuraEnabled(cacheable=true)
    public static Boolean isLoggingEnabled(String settingName) {
        
        if(Test.isRunningTest()) { //Always return false if running Tests to prevent failure as the logging can be switched on/off by the user after installation.
            return false;  
        } 
        
        List<Custom_Experience_Cloud_Setting__mdt> logSetting = new List<Custom_Experience_Cloud_Setting__mdt>();
        try {
            logSetting = [SELECT Id, Enable__c, DeveloperName
                        FROM Custom_Experience_Cloud_Setting__mdt 
                        WHERE (DeveloperName = :settingName AND Enable__c = true)
                        WITH SECURITY_ENFORCED
                        LIMIT 1];
        }
        catch(Exception ex) {
            return false;
        }
        
        if(!logSetting.isEmpty() && logSetting.size() == 1) {
            return true;
        }
        return false;
    }
}