force-app/main/default/objects/Custom_Login_Configuration__mdt/Custom_Login_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Used by the installed package called Configurable Self Registration &amp; Login For Experience Cloud to control the fields displayed on the Login form. Component behaviour is configured in Custom Experience Cloud Setting.</description>
    <label>Custom Login Configuration Fields</label>
    <pluralLabel>Custom Login Configuration Fields</pluralLabel>
</CustomObject>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Display_Order__c</fullName>
    <label>Display Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Field_Help_Text__c</fullName>
    <label>Field Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Message__c.field-meta.xml
<CustomField>
    <fullName>Field_Message__c</fullName>
    <description>Displayed if the REGEX pattern provided is not met.</description>
    <inlineHelpText>Displayed if the REGEX pattern provided is not met.</inlineHelpText>
    <label>Field REGEX Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description
  >Set this to the API Name of a field. NOTE: If invalid API Name, the field is ignored during form submission.</description>
    <inlineHelpText
  >Set this to the API Name of a field. NOTE: If invalid API Name, the field is ignored during form submission.</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Picklist_Options__c.field-meta.xml
<CustomField>
    <fullName>Field_Picklist_Options__c</fullName>
    <label>Field Picklist Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Placeholder__c.field-meta.xml
<CustomField>
    <fullName>Field_Placeholder__c</fullName>
    <label>Field Placeholder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Required__c.field-meta.xml
<CustomField>
    <fullName>Field_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Field Required</label>
    <type>Checkbox</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Required_Message__c.field-meta.xml
<CustomField>
    <fullName>Field_Required_Message__c</fullName>
    <label>Field Required Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>text</fullName>
                <default>true</default>
                <label>text</label>
            </value>
            <value>
                <fullName>password</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>tel</fullName>
            </value>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>date</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>datetime</fullName>
            </value>
            <value>
                <fullName>time</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
            <value>
                <fullName>picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Configurable Self Registration LWC/Custom Registration/force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Field_Validation_REGEX__c.field-meta.xml
<CustomField>
    <fullName>Field_Validation_REGEX__c</fullName>
    <label>Field Validation REGEX</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Login_Configuration__mdt/fields/Portal_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Portal_API_Name__c</fullName>
    <description
  >Specify the API Name by running the query: SELECT Id,Name,UrlPathPrefix FROM Site to link field configuration to a specific site, or set to &quot;ALL&quot; to display across sites where this component is used.</description>
    <inlineHelpText
  >Specify the API Name by running the query: SELECT Id,Name,UrlPathPrefix FROM Site to link field configuration to a specific site, or set to &quot;ALL&quot; to display across sites where this component is used.</inlineHelpText>
    <label>Portal API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestUtilities.cls
@istest
public without sharing class TestUtilities {
	public static List<SObject> getTestMetadata(string type) {
		list<Custom_Login_Configuration__mdt> retMetadata = new List<Custom_Login_Configuration__mdt>();
		// if (type == SiteUtilities.LOGIN_COMPONENT_NAME) {
		Custom_Login_Configuration__mdt picklist = new Custom_Login_Configuration__mdt();
		picklist.Field_Type__c = 'picklist';
		picklist.Field_Picklist_Options__c = '[{"label":"yes","value":"yes"},{"label":"no","value":"no"}]';
		picklist.Field_Placeholder__c = 'placeholder';
		picklist.Field_Message__c = 'Field_Message__c';
		picklist.Field_Help_Text__c = 'Field_Help_Text__c';
		picklist.Active__c = true;
		picklist.Portal_API_Name__c = 'ALL';
		picklist.Display_Order__c = 1;

		Custom_Login_Configuration__mdt text = new Custom_Login_Configuration__mdt();
		text.Field_Type__c = 'text';
		text.Field_Placeholder__c = 'placeholder';
		text.Field_Message__c = 'Field_Message__c';
		text.Field_Help_Text__c = 'Field_Help_Text__c';
		text.Field_Validation_REGEX__c = '.';
		text.Field_Name__c = 'email';
		text.Field_Required_Message__c = 'required field is required';
		text.Field_Required__c = true;
		text.Active__c = true;
		text.Portal_API_Name__c = 'ALL';
		Custom_Login_Configuration__mdt checkbox = new Custom_Login_Configuration__mdt();
		checkbox.Field_Type__c = 'checkbox';
		checkbox.Active__c = true;
		checkbox.Portal_API_Name__c = 'ALL';
		checkbox.Field_Name__c = 'success';

		retMetadata.add(picklist);
		retMetadata.add(text);
		retMetadata.add(checkbox);
		// }
		return retMetadata;
	}
}